[package]
name = "HostCat"
version = "0.1.0"
authors = ["dedsec"]
edition = "2018"

[dependencies]
users = "0.10.0"
clap = "3.0.0-beta.1"
better-panic = "0.2.0"

[profile.release]
opt-level = "s"
panic = "abort"